feature_map:
  name: ['101', '121', '122', '124', '125', '126', '127', '128', '129', '205', '206', '207', '210', '216', '301', '109_14', '110_14', '127_14', '150_14']
  type: ['sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'var', 'sparse', 'sparse', 'var', 'var', 'var', 'var']
  group: ["user", "user", "user", "user", "user", "user", "user", "user", "user", "item", "item", "item", "item", "item", "domain", "general", "general", "general", "general"]
embedding_dim: 4
task_num: 2
num_experts: 3
expert_hidden_units: [64, 64, 64]
gate_hidden_units: [64, 3]
tower_hidden_units: [64, 64, 1]
vocab_size: 10091403
epoch: 1
batch_size: 10240
